# See the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Infrastructure
  ## GitHub Actions
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      gh-actions:
        #applies-to: version-updates
        patterns: ["*"]
    commit-message:
      prefix: "deps(ci)"

  # authd codebase
  ## Go dependencies
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(go)"

  - package-ecosystem: "gomod"
    directory: "/tools"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(go-tools)"

  ## Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "09:00"
    groups:
      minor-updates:
        #applies-to: version-updates
        update-types: ["minor", "patch"]
    commit-message:
      prefix: "deps(rust)"

  ## git submodules
  - package-ecosystem: "gitsubmodule"
    directory: "/" # Directory containing .gitmodules
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(submodule)"

  # authd-oidc-brokers codebase
  ## Go dependencies
  - package-ecosystem: "gomod"
    directory: "/authd-oidc-brokers" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        update-types: [ "minor", "patch" ]
    commit-message:
      prefix: "deps(brokers/go)"

  - package-ecosystem: "gomod"
    directory: "/authd-oidc-brokers/tools"
    schedule:
      interval: "weekly"
    groups:
      minor-updates:
        update-types: [ "minor", "patch" ]
    commit-message:
      prefix: "deps(brokers/go-tools)"
  ## rust-toolchain.toml
  - package-ecosystem: "cargo"
    directory: "/authd-oidc-brokers"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "deps(brokers/rust)"
